export const t = {
  DE: {
    nav: { home: "Start", customers: "Kunden", catalog: "Katalog", newReport: "Neuer Rapport", reports: "Offene Rapporte", invoices: "Rechnungen", trash: "Papierkorb", settings: "Einstellungen" },
    report: { title: "Neuer Rapport", save: "Rapport speichern", customer: "Kunde", address: "Adresse", zip: "PLZ", city: "Ort", orderNo: "Auftrag-Nr", projectName: "Projektname",date: "Datum", status: "offen", statusSent: "gesendet", statusArchived: "archiviert", workHours: "Arbeitsstunden", material: "Material", expenses: "Spesen CHF", notes: "Notizen", addRow: "Zeile hinzufuegen", addPhoto: "Foto hinzufügen",employee: "Mitarbeiter", from: "Von", to: "Bis", rate: "Ansatz CHF", name: "Bezeichnung", qty: "Menge", unit: "Einheit", price: "Preis CHF", total: "Total", vat: "MwSt 8.1%", saved: "Rapport gespeichert." },
    customer: { title: "Kunden", new: "Neuer Kunde", save: "Speichern", company: "Firmenname", firstName: "Vorname", lastName: "Nachname", phone: "Telefon", email: "E-Mail", search: "Suchen..." },
    invoice: { title: "Rechnungen", new: "Neue Rechnung", save: "Speichern", generate: "Rechnung generieren", open: "Rechnung oeffnen", edit: "Bearbeiten", pdf: "PDF", sent: "Als versendet markieren", paid: "Bezahlt", discount: "Rabatt %", skonto: "Skonto %", payDays: "Zahlungsziel (Tage)", skontoDays: "Skonto-Frist (Tage)", positions: "Positionen", description: "Beschreibung", qty: "Menge", unit: "Einheit", price: "Preis CHF" },
    settings: { title: "Einstellungen", profile: "Firmenprofil", plan: "Aktueller Plan", team: "Team", legal: "Rechtliches", support: "Support", account: "Konto-Verwaltung", logout: "Logout", deactivate: "Konto deaktivieren", delete: "Konto loeschen", iban: "IBAN", logo: "Logo hochladen", nextRapportNr: "Naechste Rapport-Nr", nextInvoiceNr: "Naechste Rechnungs-Nr", nextCustomerNr: "Naechste Kunden-Nr" },
    common: { save: "Speichern", cancel: "Abbrechen", delete: "Loeschen", restore: "Wiederherstellen", edit: "Bearbeiten", search: "Suchen", loading: "Lade...", ok: "OK", back: "Zurueck", yes: "Ja", no: "Nein" },
    trash: { title: "Papierkorb", reports: "Rapporte", invoices: "Rechnungen", customers: "Kunden", empty: "Papierkorb ist leer" }
  },
  pdf: { rapport: "Rapport", invoice: "Rechnung", date: "Datum", customer: "Kunde", orderNo: "Auftrag-Nr", address: "Adresse", project: "Projekt", photos: "Fotos", before: "Vorher", after: "Nachher", workHours: "Arbeitsstunden", employee: "Mitarbeiter", time: "Zeit", hours: "Stunden", total: "Total", material: "Material / Kranrapport", description: "Bezeichnung", qty: "Menge", expenses: "Spesen", notes: "Notizen", subtotal: "Subtotal", vat: "MwSt 8.1%", draft: "ENTWURF", issuer: "Rechnungssteller", recipient: "Rechnungsempfänger", ref: "Bezug", discount: "Rabatt", payment: "Zahlung", dueDate: "Zahlbar bis", reference: "Referenz", noIban: "Keine IBAN hinterlegt", price: "Preis", skonto: "Skonto" },

  FR: {
    nav: { home: "Accueil", customers: "Clients", catalog: "Catalogue", newReport: "Nouveau rapport", reports: "Rapports ouverts", invoices: "Factures", trash: "Corbeille", settings: "Parametres" },
    report: { title: "Nouveau rapport", save: "Enregistrer", customer: "Client", address: "Adresse", zip: "NPA", city: "Lieu", orderNo: "N de commande", projectName: "Nom du projet", date: "Date", statusOpen: "ouvert", statusSent: "envoyé", statusArchived: "archivé", workHours: "Heures de travail", material: "Materiel", expenses: "Frais CHF", notes: "Remarques", addRow: "Ajouter une ligne", addPhoto: "Ajouter une photo", employee: "Employe", from: "De", to: "A", rate: "Taux CHF", name: "Designation", qty: "Quantite", unit: "Unite", price: "Prix CHF", total: "Total", vat: "TVA 8.1%", saved: "Rapport enregistre." },
    customer: { title: "Clients", new: "Nouveau client", save: "Enregistrer", company: "Nom de la societe", firstName: "Prenom", lastName: "Nom", phone: "Telephone", email: "E-mail", search: "Rechercher..." },
    invoice: { title: "Factures", new: "Nouvelle facture", save: "Enregistrer", generate: "Generer la facture", open: "Ouvrir la facture", edit: "Modifier", pdf: "PDF", sent: "Marquer comme envoyee", paid: "Payee", discount: "Rabais %", skonto: "Escompte %", payDays: "Delai de paiement (jours)", skontoDays: "Delai escompte (jours)", positions: "Positions", description: "Description", qty: "Quantite", unit: "Unite", price: "Prix CHF" },
    settings: { title: "Parametres", profile: "Profil de lentreprise", plan: "Plan actuel", team: "Equipe", legal: "Mentions legales", support: "Support", account: "Gestion du compte", logout: "Deconnexion", deactivate: "Desactiver le compte", delete: "Supprimer le compte", iban: "IBAN", logo: "Telecharger le logo", nextRapportNr: "Prochain rapport nr", nextInvoiceNr: "Prochain facture nr", nextCustomerNr: "Prochain client nr" },
    common: { save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", restore: "Restaurer", edit: "Modifier", search: "Rechercher", loading: "Chargement...", ok: "OK", back: "Retour", yes: "Oui", no: "Non" },
    trash: { title: "Corbeille", reports: "Rapports", invoices: "Factures", customers: "Clients", empty: "La corbeille est vide" }
  },
pdf: { rapport: "Rapport", invoice: "Facture", date: "Date", customer: "Client", orderNo: "N° de commande", address: "Adresse", project: "Projet", photos: "Photos", before: "Avant", after: "Après", workHours: "Heures de travail", employee: "Employé", time: "Temps", hours: "Heures", total: "Total", material: "Matériel", description: "Désignation", qty: "Quantité", expenses: "Frais", notes: "Remarques", subtotal: "Sous-total", vat: "TVA 8.1%", draft: "BROUILLON", issuer: "Émetteur", recipient: "Destinataire", ref: "Référence", discount: "Rabais", payment: "Paiement", dueDate: "Payable jusqu'au", reference: "Référence", noIban: "Pas d'IBAN enregistré", price: "Prix", skonto: "Escompte" },

  IT: {
    nav: { home: "Inizio", customers: "Clienti", catalog: "Catalogo", newReport: "Nuovo rapporto", reports: "Rapporti aperti", invoices: "Fatture", trash: "Cestino", settings: "Impostazioni" },
    report: { title: "Nuovo rapporto", save: "Salva rapporto", customer: "Cliente", address: "Indirizzo", zip: "CAP", city: "Citta", orderNo: "N ordine", projectName: "Nome del progetto", date: "Data", statusOpen: "aperto", statusSent: "inviato", statusArchived: "archiviato", workHours: "Ore di lavoro", material: "Materiale", expenses: "Spese CHF", notes: "Note", addRow: "Aggiungi riga", addPhoto: "Aggiungi foto", employee: "Dipendente", from: "Da", to: "A", rate: "Tariffa CHF", name: "Descrizione", qty: "Quantita", unit: "Unita", price: "Prezzo CHF", total: "Totale", vat: "IVA 8.1%", saved: "Rapporto salvato." },
    customer: { title: "Clienti", new: "Nuovo cliente", save: "Salva", company: "Nome azienda", firstName: "Nome", lastName: "Cognome", phone: "Telefono", email: "E-mail", search: "Cerca..." },
    invoice: { title: "Fatture", new: "Nuova fattura", save: "Salva", generate: "Genera fattura", open: "Apri fattura", edit: "Modifica", pdf: "PDF", sent: "Segna come inviata", paid: "Pagata", discount: "Sconto %", skonto: "Sconto cassa %", payDays: "Termine pagamento (giorni)", skontoDays: "Termine sconto (giorni)", positions: "Posizioni", description: "Descrizione", qty: "Quantita", unit: "Unita", price: "Prezzo CHF" },
    settings: { title: "Impostazioni", profile: "Profilo aziendale", plan: "Piano attuale", team: "Team", legal: "Note legali", support: "Supporto", account: "Gestione account", logout: "Disconnetti", deactivate: "Disattiva account", delete: "Elimina account", iban: "IBAN", logo: "Carica logo", nextRapportNr: "Prossimo rapporto nr", nextInvoiceNr: "Prossimo fattura nr", nextCustomerNr: "Prossimo cliente nr" },
    common: { save: "Salva", cancel: "Annulla", delete: "Elimina", restore: "Ripristina", edit: "Modifica", search: "Cerca", loading: "Caricamento...", ok: "OK", back: "Indietro", yes: "Si", no: "No" },
    trash: { title: "Cestino", reports: "Rapporti", invoices: "Fatture", customers: "Clienti", empty: "Il cestino e vuoto" }
  },
pdf: { rapport: "Rapporto", invoice: "Fattura", date: "Data", customer: "Cliente", orderNo: "N° ordine", address: "Indirizzo", project: "Progetto", photos: "Foto", before: "Prima", after: "Dopo", workHours: "Ore di lavoro", employee: "Dipendente", time: "Tempo", hours: "Ore", total: "Totale", material: "Materiale", description: "Descrizione", qty: "Quantità", expenses: "Spese", notes: "Note", subtotal: "Subtotale", vat: "IVA 8.1%", draft: "BOZZA", issuer: "Emittente", recipient: "Destinatario", ref: "Riferimento", discount: "Sconto", payment: "Pagamento", dueDate: "Pagabile entro", reference: "Riferimento", noIban: "Nessun IBAN registrato", price: "Prezzo", skonto: "Sconto cassa" },

  EN: {
    nav: { home: "Home", customers: "Customers", catalog: "Catalog", newReport: "New Report", reports: "Open Reports", invoices: "Invoices", trash: "Trash", settings: "Settings" },
    report: { title: "New Report", save: "Save Report", customer: "Customer", address: "Address", zip: "ZIP", city: "City", orderNo: "Order No.", projectName: "Project Name", date: "Date", statusOpen: "open", statusSent: "sent", statusArchived: "archived", workHours: "Work Hours", material: "Material", expenses: "Expenses CHF", notes: "Notes", addRow: "Add Row", addPhoto: "Add photo", employee: "Employee", from: "From", to: "To", rate: "Rate CHF", name: "Description", qty: "Quantity", unit: "Unit", price: "Price CHF", total: "Total", vat: "VAT 8.1%", saved: "Report saved." },
    customer: { title: "Customers", new: "New Customer", save: "Save", company: "Company Name", firstName: "First Name", lastName: "Last Name", phone: "Phone", email: "E-Mail", search: "Search..." },
    invoice: { title: "Invoices", new: "New Invoice", save: "Save", generate: "Generate Invoice", open: "Open Invoice", edit: "Edit", pdf: "PDF", sent: "Mark as Sent", paid: "Paid", discount: "Discount %", skonto: "Cash Discount %", payDays: "Payment Terms (days)", skontoDays: "Discount Period (days)", positions: "Positions", description: "Description", qty: "Quantity", unit: "Unit", price: "Price CHF" },
    settings: { title: "Settings", profile: "Company Profile", plan: "Current Plan", team: "Team", legal: "Legal", support: "Support", account: "Account Management", logout: "Logout", deactivate: "Deactivate Account", delete: "Delete Account", iban: "IBAN", logo: "Upload Logo", nextRapportNr: "Next Report No.", nextInvoiceNr: "Next Invoice No.", nextCustomerNr: "Next Customer No." },
    common: { save: "Save", cancel: "Cancel", delete: "Delete", restore: "Restore", edit: "Edit", search: "Search", loading: "Loading...", ok: "OK", back: "Back", yes: "Yes", no: "No" },
    trash: { title: "Trash", reports: "Reports", invoices: "Invoices", customers: "Customers", empty: "Trash is empty" }
  }
};
pdf: { rapport: "Report", invoice: "Invoice", date: "Date", customer: "Customer", orderNo: "Order No.", address: "Address", project: "Project", photos: "Photos", before: "Before", after: "After", workHours: "Work Hours", employee: "Employee", time: "Time", hours: "Hours", total: "Total", material: "Material", description: "Description", qty: "Quantity", expenses: "Expenses", notes: "Notes", subtotal: "Subtotal", vat: "VAT 8.1%", draft: "DRAFT", issuer: "Issuer", recipient: "Recipient", ref: "Reference", discount: "Discount", payment: "Payment", dueDate: "Due date", reference: "Reference", noIban: "No IBAN stored", price: "Price", skonto: "Cash discount" },

export function useTranslation(lang = "DE") {
  return t[lang] || t.DE;
}
