export const t = {
  DE: {
    nav: { home: "Start", customers: "Kunden", catalog: "Katalog", newReport: "Neuer Rapport", offerten: "Offerten", newOfferte: "Neue Offerte", reports: "Rapporte", trash: "Papierkorb", trashAutoDelete: "Elemente im Papierkorb werden nach 30 Tagen automatisch gelöscht.", email: "E-Mail", invoices: "Rechnungen", settings: "Einstellungen" },
    report: { title: "Neuer Rapport", save: "Rapport speichern", customer: "Kunde", address: "Adresse", zip: "PLZ", city: "Ort", orderNo: "Auftrag-Nr", projectName: "Projektname", date: "Datum", status: "offen", statusSent: "gesendet", statusArchived: "archiviert", statusEdited: "bearbeitet", workHours: "Arbeitsstunden", material: "Material", expenses: "Spesen CHF", notes: "Notizen", addRow: "Zeile hinzufuegen", addPhoto: "Foto hinzufuegen", employee: "Mitarbeiter", from: "Von", to: "Bis", rate: "Ansatz CHF", name: "Bezeichnung", qty: "Menge", unit: "Einheit", price: "Preis CHF", total: "Total", vat: "MwSt 8.1%", saved: "Rapport gespeichert." },
    customer: { title: "Kunden", new: "Neuer Kunde", save: "Speichern", company: "Firmenname", firstName: "Vorname", lastName: "Nachname", phone: "Telefon", email: "E-Mail", search: "Suchen..." },
    invoice: { title: "Rechnungen", new: "Neue Rechnung", draft: "Entwurf", sentLabel: "Versendet", save: "Speichern", generate: "Rechnung generieren", open: "Rechnung oeffnen", edit: "Bearbeiten", pdf: "PDF", sent: "Als versendet markieren", paid: "Bezahlt", discount: "Rabatt %", skonto: "Skonto %", payDays: "Zahlungsziel (Tage)", skontoDays: "Skonto-Frist (Tage)", positions: "Positionen", description: "Beschreibung", qty: "Menge", unit: "Einheit", price: "Preis CHF", mahnungDue30: "Mahnung fällig", mahnungCreate: "Mahnung erstellen" },
    settings: { title: "Einstellungen", profile: "Firmenprofil", plan: "Aktueller Plan", team: "Team", legal: "Rechtliches", support: "Support", account: "Konto-Verwaltung", logout: "Logout", deactivate: "Konto deaktivieren", delete: "Konto loeschen", iban: "IBAN", logo: "Logo hochladen", nextRapportNr: "Nächste Rapport-Nr", nextInvoiceNr: "Nächste Rechnungs-Nr", nextCustomerNr: "Nächste Kunden-Nr" },
    common: { save: "Speichern", cancel: "Abbrechen", delete: "Löschen", restore: "Wiederherstellen", edit: "Bearbeiten", search: "Suchen", loading: "Lade...", ok: "OK", back: "Zurück", prev: "Zurück", next: "Weiter", page: "Seite", yes: "Ja", no: "Nein", show: "Anzeigen", days: "Tage", until: "bis", mwst: "MWST-Nr", settings: { profile: "Firmenprofil", iban: "IBAN", nextReport: "Nächste Rapport-Nr", nextInvoice: "Nächste Rechnungs-Nr", nextCustomer: "Nächste Kunden-Nr", currentPlan: "Aktueller Plan", legal: "Rechtliches", imprint: "Impressum", privacy: "Datenschutz", terms: "AGB", support: "Support", account: "Konto-Verwaltung", logout: "Logout", deactivate: "Konto deaktivieren", deleteAccount: "Konto löschen", language: "Sprache", companyName: "Firmenname", phone: "Telefon", uploadLogo: "Logo hochladen", deactivateDesc: "Daten bleiben 30 Tage erhalten.", deleteDesc: "Alle Daten sofort gelöscht.", deleteAccountTitle: "Konto endgültig löschen", activatePro: "Pro Plan aktivieren (nach Zahlung)", subscribe: "Abonnieren", noLogo: "Kein Logo", profileSaved: "Firmenprofil gespeichert!", logoSaved: "Logo gespeichert!", ibanSaved: "IBAN gespeichert!", mwst: "MWST-Nr", mwstSaved: "MWST-Nr gespeichert!", user: "Benutzer", unlimited: "Unlimitiert" }, allYears: "Alle Jahre", allMonths: "Alle Monate", adminOnly: "Bearbeitung nur durch Admin möglich.", memberMode: "Mitarbeiter-Modus", invite: "Einladen", remove: "Entfernen", member: "Mitarbeiter", datenLaden: "Daten laden" },
    offerte: { title: "Offerte", details: "Offerte Details", createRapport: "Rapport erstellen", createInvoice: "Rechnung erstellen", createInvoiceFrom: "Rechnung aus Offerte erstellt.", nextOfferteNr: "Nächste Offerten-Nr.", category: "Kategorie", allCategories: "Alle", attachRapport: "Rapport anhängen", rapportSearch: "Rapport suchen (Nr., Projekt, Kunde)...", attachRapportHint: "Rapporte werden dem PDF angehängt",
      invoiceFromOfferte: "Rechnung aus Offerte", changeStatus: "Status ändern", backToCustomer: "Zurück zur Kundendatei", before: "Vorher", after: "Nachher", hours: "Std", ratePerHour: "CHF/h", subtotal: "Subtotal", deductionsTitle: "Abzüge & Konditionen", payDays: "Zahlungsziel (Tage)", skontoDays: "Skonto-Frist (Tage)", new: "Neue Offerte", save: "Offerte speichern", validUntil: "Gültig bis", status: "Status", open: "Offen", sent: "Gesendet", accepted: "Angenommen", rejected: "Abgelehnt", toRapport: "Rapport erstellen", toInvoice: "Rechnung erstellen", discount: "Rabatt %", skonto: "Skonto %", lumpsum: "Pauschalabzug CHF", deductions: "Weitere Abzüge", saved: "Offerte gespeichert.", attachReport: "Rapport anhängen", aktiv: "Aktiv", archiv: "Archiv", offerteAktiv: "Offerte Aktiv", offerteArchiv: "Offerte Archiv", noOfferten: "Keine Offerten.", openOfferten: "Offene Offerten", mahnung: "Mahnung", mahnungNr: "Mahnung Nr.", mahnungFee: "Mahngebühr CHF", mahnungNotes: "Mahnnotiz", mahnungDue: "Zahlungsfrist (Tage)", mahnungCreate: "Mahnung erstellen", mahnungDue30: "Mahnung fällig", mahnungConfirm: "Mahnung wirklich erstellen?" },
    trash: { title: "Papierkorb", reports: "Rapporte", invoices: "Rechnungen", customers: "Kunden", empty: "Papierkorb ist leer" },
    pdf: { rapport: "Rapport", invoice: "Rechnung", date: "Datum", customer: "Kunde", orderNo: "Auftrag-Nr", address: "Adresse", project: "Projekt", photos: "Fotos", before: "Vorher", after: "Nachher", workHours: "Arbeitsstunden", employee: "Mitarbeiter", time: "Zeit", hours: "Stunden", total: "Total", material: "Material", description: "Bezeichnung", qty: "Menge", expenses: "Spesen", notes: "Notizen", subtotal: "Subtotal", vat: "MwSt 8.1%", draft: "ENTWURF", issuer: "Rechnungssteller", recipient: "Rechnungsempfaenger", ref: "Bezug", discount: "Rabatt", payment: "Zahlung", dueDate: "Zahlbar bis", reference: "Referenz", noIban: "Keine IBAN hinterlegt", price: "Preis", skonto: "Skonto", print: "PDF/Drucken", email: "E-Mail"}
    },
  FR: {
    nav: { home: "Accueil", customers: "Clients", catalog: "Catalogue", newReport: "Nouveau rapport", offerten: "Offres", newOfferte: "Nouvelle offre", reports: "Rapports", trash: "Corbeille", trashAutoDelete: "Les éléments dans la corbeille sont automatiquement supprimés après 30 jours.", email: "E-Mail", invoices: "Factures", settings: "Parametres" },
    report: { title: "Nouveau rapport", save: "Enregistrer", customer: "Client", address: "Adresse", zip: "NPA", city: "Lieu", orderNo: "N de commande", projectName: "Nom du projet", date: "Date", status: "ouvert", statusSent: "envoye", statusArchived: "archive", statusEdited: "en cours", workHours: "Heures de travail", material: "Materiel", expenses: "Frais CHF", notes: "Remarques", addRow: "Ajouter une ligne", addPhoto: "Ajouter une photo", employee: "Employe", from: "De", to: "A", rate: "Taux CHF", name: "Designation", qty: "Quantite", unit: "Unite", price: "Prix CHF", total: "Total", vat: "TVA 8.1%", saved: "Rapport enregistre." },
    customer: { title: "Clients", new: "Nouveau client", save: "Enregistrer", company: "Nom de la societe", firstName: "Prenom", lastName: "Nom", phone: "Telephone", email: "E-mail", search: "Rechercher..." },
    invoice: { title: "Factures", new: "Nouvelle facture", draft: "Brouillon", sentLabel: "Envoyee", save: "Enregistrer", generate: "Generer la facture", open: "Ouvrir la facture", edit: "Modifier", pdf: "PDF", sent: "Marquer comme envoyee", paid: "Payee", discount: "Rabais %", skonto: "Escompte %", payDays: "Delai de paiement (jours)", skontoDays: "Delai escompte (jours)", positions: "Positions", description: "Description", qty: "Quantite", unit: "Unite", price: "Prix CHF", mahnungDue30: "Rappel dû", mahnungCreate: "Créer rappel" },
    settings: { title: "Parametres", profile: "Profil de lentreprise", plan: "Plan actuel", team: "Equipe", legal: "Mentions legales", support: "Support", account: "Gestion du compte", logout: "Deconnexion", deactivate: "Desactiver le compte", delete: "Supprimer le compte", iban: "IBAN", logo: "Telecharger le logo", nextRapportNr: "Prochain rapport nr", nextInvoiceNr: "Prochain facture nr", nextCustomerNr: "Prochain client nr" },
    common: { save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", restore: "Restaurer", edit: "Modifier", search: "Rechercher", loading: "Chargement...", ok: "OK", back: "Retour", prev: "Précédent", next: "Suivant", page: "Page", yes: "Oui", no: "Non", show: "Afficher", days: "jours", until: "au", mwst: "No TVA", settings: { profile: "Profil entreprise", iban: "IBAN", nextReport: "Prochain rapport", nextInvoice: "Prochaine facture", nextCustomer: "Prochain client", currentPlan: "Plan actuel", legal: "Mentions legales", imprint: "Mentions", privacy: "Protection des donnees", terms: "CGV", support: "Support", account: "Gestion du compte", logout: "Deconnexion", deactivate: "Desactiver le compte", deleteAccount: "Supprimer le compte", language: "Langue", companyName: "Nom entreprise", phone: "Telephone", uploadLogo: "Telecharger logo", deactivateDesc: "Donnees conservees 30 jours.", deleteDesc: "Toutes les donnees supprimees.", deleteAccountTitle: "Supprimer definitivement", activatePro: "Activer Pro (apres paiement)", subscribe: "S'abonner", noLogo: "Pas de logo", profileSaved: "Profil enregistre!", logoSaved: "Logo enregistre!", ibanSaved: "IBAN enregistre!", mwst: "No TVA", mwstSaved: "No TVA enregistre!", user: "Utilisateur", unlimited: "Illimite" }, allYears: "Toutes les annnées", allMonths: "Tous les mois" },    
    offerte: { title: "Offres", details: "Détails de l'offre", createRapport: "Créer rapport", createInvoice: "Créer facture", createInvoiceFrom: "Facture créée depuis offre.", nextOfferteNr: "Prochain n° offre", category: "Catégorie", allCategories: "Toutes", attachRapport: "Joindre rapport", rapportSearch: "Chercher rapport (n°, projet, client)...", attachRapportHint: "Les rapports seront joints au PDF",
      invoiceFromOfferte: "Facture depuis offre", changeStatus: "Changer statut", backToCustomer: "Retour au client", before: "Avant", after: "Après", hours: "Hrs", ratePerHour: "CHF/h", subtotal: "Sous-total", deductionsTitle: "Déductions & Conditions", payDays: "Délai de paiement (jours)", skontoDays: "Délai escompte (jours)", new: "Nouvelle offre", save: "Enregistrer", validUntil: "Valable jusqu au", status: "Statut", open: "Ouverte", sent: "Envoyée", accepted: "Acceptée", rejected: "Refusée", toRapport: "Créer rapport", toInvoice: "Créer facture", discount: "Rabais %", skonto: "Escompte %", lumpsum: "Déduction forfaitaire CHF", deductions: "Autres déductions", saved: "Offre enregistrée.", attachReport: "Joindre rapport", aktiv: "Actives", archiv: "Archives", offerteAktiv: "Offres actives", offerteArchiv: "Offres archivées", noOfferten: "Aucune offre.", openOfferten: "Offres ouvertes", mahnung: "Rappel", mahnungNr: "Rappel N°", mahnungFee: "Frais de rappel CHF", mahnungNotes: "Note de rappel", mahnungDue: "Délai de paiement (jours)", mahnungCreate: "Créer rappel", mahnungDue30: "Rappel dû", mahnungConfirm: "Créer le rappel?" },
    trash: { title: "Corbeille", reports: "Rapports", invoices: "Factures", customers: "Clients", empty: "La corbeille est vide" },
    pdf: { rapport: "Rapport", invoice: "Facture", date: "Date", customer: "Client", orderNo: "N de commande", address: "Adresse", project: "Projet", photos: "Photos", before: "Avant", after: "Apres", workHours: "Heures de travail", employee: "Employe", time: "Temps", hours: "Heures", total: "Total", material: "Materiel", description: "Designation", qty: "Quantite", expenses: "Frais", notes: "Remarques", subtotal: "Sous-total", vat: "TVA 8.1%", draft: "BROUILLON", issuer: "Emetteur", recipient: "Destinataire", ref: "Reference", discount: "Rabais", payment: "Paiement", dueDate: "Payable jusqu au", reference: "Reference", noIban: "Pas d IBAN enregistre", price: "Prix", skonto: "Escompte", print: "PDF/Imprimer", email: "E-Mail"}
  },
  IT: {
    nav: { home: "Inizio", customers: "Clienti", catalog: "Catalogo", newReport: "Nuovo rapporto", offerten: "Offerte", newOfferte: "Nuova offerta", reports: "Rapporti", trash: "Cestino", trashAutoDelete: "Gli elementi nel cestino vengono eliminati automaticamente dopo 30 giorni.", email: "E-Mail", invoices: "Fatture", settings: "Impostazioni" },
    report: { title: "Nuovo rapporto", save: "Salva rapporto", customer: "Cliente", address: "Indirizzo", zip: "CAP", city: "Citta", orderNo: "N ordine", projectName: "Nome del progetto", date: "Data", status: "aperto", statusSent: "inviato", statusArchived: "archiviato", statusEdited: "in lavorazione", workHours: "Ore di lavoro", material: "Materiale", expenses: "Spese CHF", notes: "Note", addRow: "Aggiungi riga", addPhoto: "Aggiungi foto", employee: "Dipendente", from: "Da", to: "A", rate: "Tariffa CHF", name: "Descrizione", qty: "Quantita", unit: "Unita", price: "Prezzo CHF", total: "Totale", vat: "IVA 8.1%", saved: "Rapporto salvato." },
    customer: { title: "Clienti", new: "Nuovo cliente", save: "Salva", company: "Nome azienda", firstName: "Nome", lastName: "Cognome", phone: "Telefono", email: "E-mail", search: "Cerca..." },
    invoice: { title: "Fatture", new: "Nuova fattura", draft: "Bozza", sentLabel: "Inviata", save: "Salva", generate: "Genera fattura", open: "Apri fattura", edit: "Modifica", pdf: "PDF", sent: "Segna come inviata", paid: "Pagata", discount: "Sconto %", skonto: "Sconto cassa %", payDays: "Termine pagamento (giorni)", skontoDays: "Termine sconto (giorni)", positions: "Posizioni", description: "Descrizione", qty: "Quantita", unit: "Unita", price: "Prezzo CHF", mahnungDue30: "Sollecito dovuto", mahnungCreate: "Crea sollecito" },
    settings: { title: "Impostazioni", profile: "Profilo aziendale", plan: "Piano attuale", team: "Team", legal: "Note legali", support: "Supporto", account: "Gestione account", logout: "Disconnetti", deactivate: "Disattiva account", delete: "Elimina account", iban: "IBAN", logo: "Carica logo", nextRapportNr: "Prossimo rapporto nr", nextInvoiceNr: "Prossimo fattura nr", nextCustomerNr: "Prossimo cliente nr" },
    common: { save: "Salva", cancel: "Annulla", delete: "Elimina", restore: "Ripristina", edit: "Modifica", search: "Cerca", loading: "Caricamento...", ok: "OK", back: "Indietro", prev: "Precedente", next: "Avanti", page: "Pagina", yes: "Si", no: "No", show: "Mostra", days: "giorni", until: "al", mwst: "N. IVA", settings: { profile: "Profilo aziendale", iban: "IBAN", nextReport: "Prossimo rapporto", nextInvoice: "Prossima fattura", nextCustomer: "Prossimo cliente", currentPlan: "Piano attuale", legal: "Note legali", imprint: "Impressum", privacy: "Privacy", terms: "CGC", support: "Supporto", account: "Gestione account", logout: "Disconnetti", deactivate: "Disattiva account", deleteAccount: "Elimina account", language: "Lingua", companyName: "Nome azienda", phone: "Telefono", uploadLogo: "Carica logo", deactivateDesc: "Dati conservati 30 giorni.", deleteDesc: "Tutti i dati eliminati.", deleteAccountTitle: "Elimina definitivamente", activatePro: "Attiva Pro (dopo pagamento)", subscribe: "Abbonati", noLogo: "Nessun logo", profileSaved: "Profilo salvato!", logoSaved: "Logo salvato!", ibanSaved: "IBAN salvato!", mwst: "N. IVA", mwstSaved: "N. IVA salvato!", user: "Utente", unlimited: "Illimitato" }, allYears: "Tutti gli anni", allMonths: "Tutti i mesi", adminOnly: "Modifica riservata all'admin.", memberMode: "Modalità dipendente", invite: "Invita", remove: "Rimuovi", member: "Dipendente", datenLaden: "Carica dati" },    
    offerte: { title: "Offerte", before: "Prima", after: "Dopo", hours: "Ore", ratePerHour: "CHF/h", subtotal: "Subtotale", deductionsTitle: "Deduzioni & Condizioni", payDays: "Termine pagamento (giorni)", skontoDays: "Termine sconto (giorni)", new: "Nuova offerta", save: "Salva", validUntil: "Valido fino al", status: "Stato", open: "Aperta", sent: "Inviata", accepted: "Accettata", rejected: "Rifiutata", toRapport: "Crea rapporto", toInvoice: "Crea fattura", discount: "Sconto %", skonto: "Sconto cassa %", lumpsum: "Deduzione forfettaria CHF", deductions: "Altre deduzioni", saved: "Offerta salvata.", attachReport: "Allega rapporto", aktiv: "Attive", archiv: "Archivio", offerteAktiv: "Offerte attive", offerteArchiv: "Offerte archiviate", noOfferten: "Nessuna offerta.", openOfferten: "Offerte aperte", mahnung: "Sollecito", mahnungNr: "Sollecito N.", mahnungFee: "Spese sollecito CHF", mahnungNotes: "Nota sollecito", mahnungDue: "Termine pagamento (giorni)", mahnungCreate: "Crea sollecito", mahnungDue30: "Sollecito dovuto", mahnungConfirm: "Creare il sollecito?" },
    trash: { title: "Cestino", reports: "Rapporti", invoices: "Fatture", customers: "Clienti", empty: "Il cestino e vuoto" },
    pdf: { rapport: "Rapporto", invoice: "Fattura", date: "Data", customer: "Cliente", orderNo: "N ordine", address: "Indirizzo", project: "Progetto", photos: "Foto", before: "Prima", after: "Dopo", workHours: "Ore di lavoro", employee: "Dipendente", time: "Tempo", hours: "Ore", total: "Totale", material: "Materiale", description: "Descrizione", qty: "Quantita", expenses: "Spese", notes: "Note", subtotal: "Subtotale", vat: "IVA 8.1%", draft: "BOZZA", issuer: "Emittente", recipient: "Destinatario", ref: "Riferimento", discount: "Sconto", payment: "Pagamento", dueDate: "Pagabile entro", reference: "Riferimento", noIban: "Nessun IBAN registrato", price: "Prezzo", skonto: "Sconto cassa", print: "PDF/Stampa", email: "E-Mail"}
  },
  EN: {
    nav: { home: "Home", customers: "Customers", catalog: "Catalog", newReport: "New Report", offerten: "Quotes", newOfferte: "New Quote", reports: "Reports", trash: "Trash", trashAutoDelete: "Items in the trash are automatically deleted after 30 days.", email: "E-Mail", invoices: "Invoices", settings: "Settings" },
    report: { title: "New Report", save: "Save Report", customer: "Customer", address: "Address", zip: "ZIP", city: "City", orderNo: "Order No.", projectName: "Project Name", date: "Date", status: "open", statusSent: "sent", statusArchived: "archived", statusEdited: "in progress", workHours: "Work Hours", material: "Material", expenses: "Expenses CHF", notes: "Notes", addRow: "Add Row", addPhoto: "Add photo", employee: "Employee", from: "From", to: "To", rate: "Rate CHF", name: "Description", qty: "Quantity", unit: "Unit", price: "Price CHF", total: "Total", vat: "VAT 8.1%", saved: "Report saved." },
    customer: { title: "Customers", new: "New Customer", save: "Save", company: "Company Name", firstName: "First Name", lastName: "Last Name", phone: "Phone", email: "E-Mail", search: "Search..." },
    invoice: { title: "Invoices", new: "New Invoice", draft: "Draft", sentLabel: "Sent", save: "Save", generate: "Generate Invoice", open: "Open Invoice", edit: "Edit", pdf: "PDF", sent: "Mark as Sent", paid: "Paid", discount: "Discount %", skonto: "Cash Discount %", payDays: "Payment Terms (days)", skontoDays: "Discount Period (days)", positions: "Positions", description: "Description", qty: "Quantity", unit: "Unit", price: "Price CHF", mahnungDue30: "Reminder due", mahnungCreate: "Create reminder" },
    settings: { title: "Settings", profile: "Company Profile", plan: "Current Plan", team: "Team", legal: "Legal", support: "Support", account: "Account Management", logout: "Logout", deactivate: "Deactivate Account", delete: "Delete Account", iban: "IBAN", logo: "Upload Logo", nextRapportNr: "Next Report No.", nextInvoiceNr: "Next Invoice No.", nextCustomerNr: "Next Customer No." },
    common: { save: "Save", cancel: "Cancel", delete: "Delete", restore: "Restore", edit: "Edit", search: "Search", loading: "Loading...", ok: "OK", back: "Back", prev: "Previous", next: "Next", page: "Page", yes: "Yes", no: "No", show: "Show", days: "days", until: "until", mwst: "VAT No.", settings: { profile: "Company Profile", iban: "IBAN", nextReport: "Next Report No", nextInvoice: "Next Invoice No", nextCustomer: "Next Customer No", currentPlan: "Current Plan", legal: "Legal", imprint: "Imprint", privacy: "Privacy", terms: "Terms", support: "Support", account: "Account Management", logout: "Logout", deactivate: "Deactivate Account", deleteAccount: "Delete Account", language: "Language", companyName: "Company Name", phone: "Phone", uploadLogo: "Upload Logo", deactivateDesc: "Data kept 30 days.", deleteDesc: "All data deleted immediately.", deleteAccountTitle: "Delete permanently", activatePro: "Activate Pro (after payment)", subscribe: "Subscribe", noLogo: "No Logo", profileSaved: "Profile saved!", logoSaved: "Logo saved!", ibanSaved: "IBAN saved!", mwst: "VAT No.", mwstSaved: "VAT No. saved!", user: "User", unlimited: "Unlimited" }, allYears: "All years", allMonths: "All months", adminOnly: "Only admin can edit.", memberMode: "Employee Mode", invite: "Invite", remove: "Remove", member: "Employee", datenLaden: "Load data" },   
    offerte: { title: "Quotes", details: "Quote Details", createRapport: "Create Report", createInvoice: "Create Invoice", createInvoiceFrom: "Invoice created from quote.", nextOfferteNr: "Next Quote No.", category: "Category", allCategories: "All", attachRapport: "Attach Report", rapportSearch: "Search report (no., project, customer)...", attachRapportHint: "Reports will be attached to PDF",
      invoiceFromOfferte: "Invoice from Quote", changeStatus: "Change Status", backToCustomer: "Back to Customer", before: "Before", after: "After", hours: "Hrs", ratePerHour: "CHF/h", subtotal: "Subtotal", deductionsTitle: "Deductions & Conditions", payDays: "Payment Terms (days)", skontoDays: "Discount Period (days)", new: "New Quote", save: "Save Quote", validUntil: "Valid until", status: "Status", open: "Open", sent: "Sent", accepted: "Accepted", rejected: "Rejected", toRapport: "Create Report", toInvoice: "Create Invoice", discount: "Discount %", skonto: "Cash Discount %", lumpsum: "Lump Sum Deduction CHF", deductions: "Further Deductions", saved: "Quote saved.", attachReport: "Attach Report", aktiv: "Active", archiv: "Archive", offerteAktiv: "Quotes Active", offerteArchiv: "Quotes Archive", noOfferten: "No quotes.", openOfferten: "Open Quotes", mahnung: "Reminder", mahnungNr: "Reminder No.", mahnungFee: "Reminder fee CHF", mahnungNotes: "Reminder note", mahnungDue: "Payment deadline (days)", mahnungCreate: "Create reminder", mahnungDue30: "Reminder due", mahnungConfirm: "Create reminder?" },
    trash: { title: "Trash", reports: "Reports", invoices: "Invoices", customers: "Customers", empty: "Trash is empty" },
    pdf: { rapport: "Report", invoice: "Invoice", date: "Date", customer: "Customer", orderNo: "Order No.", address: "Address", project: "Project", photos: "Photos", before: "Before", after: "After", workHours: "Work Hours", employee: "Employee", time: "Time", hours: "Hours", total: "Total", material: "Material", description: "Description", qty: "Quantity", expenses: "Expenses", notes: "Notes", subtotal: "Subtotal", vat: "VAT 8.1%", draft: "DRAFT", issuer: "Issuer", recipient: "Recipient", ref: "Reference", discount: "Discount", payment: "Payment", dueDate: "Due date", reference: "Reference", noIban: "No IBAN stored", price: "Price", skonto: "Cash discount", print: "PDF/Print", email: "E-Mail"}
  }
};

export function useTranslation(lang) {
  return t[lang] || t.DE;
}
