import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://tgtyuxtrrafxalajxenw.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndHl1eHRycmFmeGFsYWp4ZW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NjMzOTYsImV4cCI6MjA4OTIzOTM5Nn0.ePbGVxCbj_mr_RMLtf4uphnvxdx267QmTfTuMknPhK8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { autoRefreshToken: true, persistSession: true, detectSessionInUrl: true } });

// SQL to create required application tables in Supabase SQL editor.
export const TABLE_SETUP_SQL = {
  reports: `
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer text not null,
  status text not null default 'open',
  date date not null default current_date,
  description text default ''
);
`,
  customers: `
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  address text default '',
  phone text default '',
  email text default ''
);
`,
  projects: `
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  name text not null,
  projektnummer text default '',
  created_at timestamptz not null default now()
);
`
};

export async function fetchReports(userId) {
  return supabase
    .from("reports")
    .select("id, user_id, customer, status, date, description")
    .eq("user_id", userId)
    .order("date", { ascending: false });
}

export async function createReport(payload) {
  return supabase.from("reports").insert(payload).select().single();
}

export async function fetchCustomers(userId) {
  return supabase
    .from("customers")
    .select("id, user_id, name, address, phone, email")
    .eq("user_id", userId)
    .order("name", { ascending: true });
}

export async function fetchProjectsByCustomer(customerId) {
  return supabase
    .from("projects")
    .select("id, customer_id, name, projektnummer, created_at")
    .eq("customer_id", customerId)
    .order("created_at", { ascending: false });
}

export async function createProject(payload) {
  return supabase.from("projects").insert(payload).select().single();
}
